version: "3"

services:
  database:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "ki11_m3_pl3453hahaaha"
    volumes:
      - ./postgres/create_db.sql:/docker-entrypoint-initdb.d/init.sql
  tiny_user_system:
    image: tiny_user_system_image
    build:
      context: .
    ports:
      - "3003:3003"
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database

